Require additional multipart upload permissions
Error: Unexpected exception in upload:
Traceback (most recent call last):
  File "./server-backup-s3", line 674, in main
    backup.get_pipe()
  File "./server-backup-s3", line 301, in multipart_from_process
    self.bucket.get_all_multipart_uploads():
  File "/usr/lib/python2.7/dist-packages/boto/s3/bucket.py", line 609, in get_all_multipart_uploads
    'uploads', headers, **params)
  File "/usr/lib/python2.7/dist-packages/boto/s3/bucket.py", line 410, in _get_all
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 403 Forbidden